SELECT ?subject ?subjectLabel ?property ?propertyLabel ?item ?itemLabel
WHERE {
  ?subject wdt:P1435 ?item .
  BIND(wd:P1435 AS ?property)

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
LIMIT 50